version: '3.9'

services:
  pg-database:
    image: postgres:16
    container_name: pg-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: green_taxi
    volumes:
      - green_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - taxi-network

  homework_ingest:
    image: homework_ingest:v1
    container_name: homework_ingest
    depends_on:
      - pg-database
    networks:
      - taxi-network
    command: >
      --pg-user=root
      --pg-pass=root
      --pg-host=pg-database
      --pg-port=5432
      --pg-database=green_taxi
      --year=2025
      --month=11
      --pg-batch-size=10000

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - taxi-network

volumes:
  green_taxi_postgres_data:
  pgadmin_data:

networks:
  taxi-network:
    driver: bridge
